# Build config for ebay-java-oauth-client
language: java
dist: trusty

os:
  - linux

sudo: required
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - sh -e /etc/init.d/xvfb start
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver