# Build config for ebay-java-oauth-client
language: java

os:
  - linux

sudo: required
addons:
  apt:
  packages:
    - chromium-chromedriver

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver